### ISSUE TITLE
NPE from JavaFX Application Thread

### ISSUE THREAD

**Issue by karlduderstadt** [duderstadt-lab/mars-fx#62]
Sometimes when working with the mars archive windows this error pops up:

```
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at com.sun.javafx.tk.quantum.QuantumToolkit.isSupported(QuantumToolkit.java:1197)
	at com.sun.javafx.application.PlatformImpl.isSupportedImpl(PlatformImpl.java:809)
	at com.sun.javafx.application.PlatformImpl.isSupported(PlatformImpl.java:482)
	at javafx.application.Platform.isSupported(Platform.java:171)
	at com.sun.javafx.scene.input.PickResultChooser.processOffer(PickResultChooser.java:182)
	at com.sun.javafx.scene.input.PickResultChooser.offer(PickResultChooser.java:143)
	at javafx.scene.Node.impl_computeIntersects(Node.java:4980)
	at javafx.scene.Node.impl_intersects(Node.java:4947)
	at javafx.scene.Node.impl_pickNodeLocal(Node.java:4877)
	at javafx.scene.Node.impl_pickNode(Node.java:4912)
	at javafx.scene.layout.Region.impl_pickNodeLocal(Region.java:2936)
	at javafx.scene.Node.impl_pickNode(Node.java:4912)
	at javafx.scene.layout.Region.impl_pickNodeLocal(Region.java:2936)
	at javafx.scene.Node.impl_pickNode(Node.java:4912)
	at javafx.scene.layout.Region.impl_pickNodeLocal(Region.java:2936)
	at javafx.scene.Node.impl_pickNode(Node.java:4912)
	at javafx.scene.layout.Region.impl_pickNodeLocal(Region.java:2936)
	at javafx.scene.Node.impl_pickNode(Node.java:4912)
	at javafx.scene.layout.Region.impl_pickNodeLocal(Region.java:2936)
	at javafx.scene.Node.impl_pickNode(Node.java:4912)
	at javafx.scene.layout.Region.impl_pickNodeLocal(Region.java:2936)
	at javafx.scene.Node.impl_pickNode(Node.java:4912)
	at javafx.scene.layout.Region.impl_pickNodeLocal(Region.java:2936)
	at javafx.scene.Node.impl_pickNode(Node.java:4912)
	at javafx.scene.layout.Region.impl_pickNodeLocal(Region.java:2936)
	at javafx.scene.Node.impl_pickNode(Node.java:4912)
	at javafx.scene.layout.Region.impl_pickNodeLocal(Region.java:2936)
	at javafx.scene.Node.impl_pickNode(Node.java:4912)
	at javafx.scene.layout.Region.impl_pickNodeLocal(Region.java:2936)
	at javafx.scene.Node.impl_pickNode(Node.java:4912)
	at javafx.scene.layout.Region.impl_pickNodeLocal(Region.java:2936)
	at javafx.scene.Node.impl_pickNode(Node.java:4912)
	at javafx.scene.layout.Region.impl_pickNodeLocal(Region.java:2936)
	at javafx.scene.Node.impl_pickNode(Node.java:4912)
	at javafx.scene.layout.Region.impl_pickNodeLocal(Region.java:2936)
	at javafx.scene.Node.impl_pickNode(Node.java:4912)
	at javafx.scene.layout.Region.impl_pickNodeLocal(Region.java:2936)
	at javafx.scene.Node.impl_pickNode(Node.java:4912)
	at javafx.scene.layout.Region.impl_pickNodeLocal(Region.java:2936)
	at javafx.scene.Node.impl_pickNode(Node.java:4912)
	at javafx.scene.layout.Region.impl_pickNodeLocal(Region.java:2936)
	at javafx.scene.Node.impl_pickNode(Node.java:4912)
	at javafx.scene.layout.Region.impl_pickNodeLocal(Region.java:2936)
	at javafx.scene.Node.impl_pickNode(Node.java:4912)
	at javafx.scene.layout.Region.impl_pickNodeLocal(Region.java:2936)
	at javafx.scene.Node.impl_pickNode(Node.java:4912)
	at javafx.scene.layout.Region.impl_pickNodeLocal(Region.java:2936)
	at javafx.scene.Node.impl_pickNode(Node.java:4912)
	at javafx.scene.layout.Region.impl_pickNodeLocal(Region.java:2936)
	at javafx.scene.Node.impl_pickNode(Node.java:4912)
	at javafx.scene.layout.Region.impl_pickNodeLocal(Region.java:2936)
	at javafx.scene.Node.impl_pickNode(Node.java:4912)
	at javafx.scene.layout.Region.impl_pickNodeLocal(Region.java:2936)
	at javafx.scene.Node.impl_pickNode(Node.java:4912)
	at javafx.scene.Scene$MouseHandler.pickNode(Scene.java:3902)
	at javafx.scene.Scene$MouseHandler.access$1600(Scene.java:3488)
	at javafx.scene.Scene.pick(Scene.java:1945)
	at javafx.scene.Scene.access$6700(Scene.java:159)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3714)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3488)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1765)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2497)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:394)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:432)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:411)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:431)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
```

Could it be related to how windows are closed or perhaps related to this [post](https://stackoverflow.com/questions/67420780/javafx-exception-in-thread-javafx-application-thread-java-lang-nullpointerexc)?

**Comment by karlduderstadt** [comment]
This issue is fixed since the migration to JavaFX 23 and dark mode incorporation.
